# name: CI Pipeline

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     # Checkout the repository code
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     # Set up Java environment
#     - name: Set up JDK 11
#       uses: actions/setup-java@v3
#       with:
#         java-version: 11
#         distribution: temurin

#     # Cache Gradle dependencies
#     - name: Cache Gradle dependencies
#       uses: actions/cache@v3
#       with:
#         path: ~/.gradle/caches
#         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#         restore-keys: |
#           ${{ runner.os }}-gradle-

#     # Build the application
#     - name: Build with Gradle
#       run: ./gradlew assemble

#     # Run tests
#     - name: Run Tests
#       run: ./gradlew test

#     # Archive test results (optional)
#     - name: Upload Test Results
#       if: always()
#       uses: actions/upload-artifact@v3
#       with:
#         name: test-results
#         path: build/test-results/**/*.xml
